FROM python:3.10-slim

WORKDIR /app

COPY ./app /app/app
COPY ./requirements.txt /app/requirements.txt
COPY ./.env /app/.env

RUN pip install --no-cache-dir -r /app/requirements.txt

EXPOSE 7860

CMD ["uvicorn", "app.bot_webhook:app", "--host", "0.0.0.0", "--port", "7860"]
